# version: '3'

services:
  web_dynamic:
    build:
      context: .  # 親ディレクトリをビルドコンテキストに指定
      dockerfile: web_dynamic/Dockerfile
    environment:
      HBNB_MYSQL_USER: hbnb_dev
      HBNB_MYSQL_PWD: hbnb_dev_pwd
      HBNB_MYSQL_HOST: 127.0.0.1
      HBNB_MYSQL_DB: hbnb_dev_db
      HBNB_TYPE_STORAGE: db
    command: python3 -m web_dynamic.hbnb
    ports:
      - "5000:5000"
    networks:
      - hbnb-network

  api:
    build:
      context: .  # 親ディレクトリをビルドコンテキストに指定
      dockerfile: api/Dockerfile
    environment:
      HBNB_MYSQL_USER: hbnb_dev
      HBNB_MYSQL_PWD: hbnb_dev_pwd
      HBNB_MYSQL_HOST: 127.0.0.1
      HBNB_MYSQL_DB: hbnb_dev_db
      HBNB_TYPE_STORAGE: db
      HBNB_API_PORT: 5001
    command: python3 -m api.v1.app
    ports:
      - "5001:5001"
    networks:
      - hbnb-network

networks:
  hbnb-network:
    driver: bridge
